language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libboost-dev valgrind
script:
  - mkdir build 
  - cd build
  - cmake ..
  - make
  - make test
after_script:
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/packets/packets
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/simple/simple
